repos:
-   repo: local
    hooks:
    -   id: exif-cleanup
        name: Remove GPS via Exiftool
        entry: exiftool -all= -tagsfromfile @ -datetimeoriginal -orientation -colorspace -icc_profile -overwrite_original
        language: system
        files: '(?i)\.(jpg|jpeg|png)$'
        pass_filenames: true
